### GET /info
GET http://localhost:5000/info
Accept: application/json


### POST /crear_usuario
POST http://localhost:5000/crear_usuario
Content-Type: application/json

{
    "nombre": "Carlos Garcia",
    "correo": "carlos@correo.com"
}


### GET /usuarios
GET http://localhost:5000/usuarios
Accept: application/json
